version: "3.8"
services:

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

  rest-api:
    image: tlebreton/mongo_rest
    ports:
      - "8080:8080"
    links:
      - mongodb